Load 3.3.387 into branch/prcs-import-33.
git-svn-id: svn://svn.bearnip.com/ldmud/branch/prcs-import-33@840 56160b6e-f8f8-0310-bd54-bccebfe6a2f2

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -8683,62 +8683,8 @@ if test $lp_cv_has_pthreads = yes; then
 #define HAS_PTHREADS 1
 _ACEOF
 
-    echo "$as_me:$LINENO: checking for pthread_atfork()" >&5
-echo $ECHO_N "checking for pthread_atfork()... $ECHO_C" >&6
-if test "${lp_cv_has_pthread_atfork+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
 
-#include <pthread.h>
-void t (void)
-{
-    pthread_atfork(0, 0, 0);
-}
-
-int
-main ()
-{
-
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  lp_cv_has_pthread_atfork=yes
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-lp_cv_has_pthread_atfork=no
-
-fi
-rm -f conftest.$ac_objext conftest.$ac_ext
-
-fi
-echo "$as_me:$LINENO: result: $lp_cv_has_pthread_atfork" >&5
-echo "${ECHO_T}$lp_cv_has_pthread_atfork" >&6
-    if test $lp_cv_has_pthread_atfork = yes; then
-        cat >>confdefs.h <<\_ACEOF
-#define HAS_PTHREAD_ATFORK 1
-_ACEOF
-
-    fi
-
-    if test $enable_use_pthreads = yes; then
-        echo "$as_me:$LINENO: checking if -lpthread or similar is needed" >&5
+    echo "$as_me:$LINENO: checking if -lpthread or similar is needed" >&5
 echo $ECHO_N "checking if -lpthread or similar is needed... $ECHO_C" >&6
 if test "${lp_cv_need_lib_pthread+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -8789,9 +8735,9 @@ fi
 fi
 echo "$as_me:$LINENO: result: $lp_cv_need_lib_pthread" >&5
 echo "${ECHO_T}$lp_cv_need_lib_pthread" >&6
-        if test "$lp_cv_need_lib_pthread" = "yes"; then
-            lp_cv_has_lib_pthread=no
-            echo "$as_me:$LINENO: checking for main in -lpthread" >&5
+    if test "$lp_cv_need_lib_pthread" = "yes"; then
+        lp_cv_has_lib_pthread=no
+        echo "$as_me:$LINENO: checking for main in -lpthread" >&5
 echo $ECHO_N "checking for main in -lpthread... $ECHO_C" >&6
 if test "${ac_cv_lib_pthread_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -8836,12 +8782,12 @@ echo "$as_me:$LINENO: result: $ac_cv_lib_pthread_main" >&5
 echo "${ECHO_T}$ac_cv_lib_pthread_main" >&6
 if test $ac_cv_lib_pthread_main = yes; then
   LIBS="$LIBS -lpthread"
-                         lp_cv_has_lib_pthread=yes
+                     lp_cv_has_lib_pthread=yes
 
 fi
 
-            if test "$lp_cv_has_lib_pthread" = "no"; then
-                echo "$as_me:$LINENO: checking for main in -lc_r" >&5
+        if test "$lp_cv_has_lib_pthread" = "no"; then
+            echo "$as_me:$LINENO: checking for main in -lc_r" >&5
 echo $ECHO_N "checking for main in -lc_r... $ECHO_C" >&6
 if test "${ac_cv_lib_c_r_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -8886,13 +8832,67 @@ echo "$as_me:$LINENO: result: $ac_cv_lib_c_r_main" >&5
 echo "${ECHO_T}$ac_cv_lib_c_r_main" >&6
 if test $ac_cv_lib_c_r_main = yes; then
   LIBS="$LIBS -lc_r"
-                             lp_cv_has_lib_pthread=yes
+                         lp_cv_has_lib_pthread=yes
 
 fi
 
-            fi
         fi
     fi
+
+    echo "$as_me:$LINENO: checking for pthread_atfork()" >&5
+echo $ECHO_N "checking for pthread_atfork()... $ECHO_C" >&6
+if test "${lp_cv_has_pthread_atfork+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling" >&5
+echo "$as_me: error: cannot run test program while cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#include <pthread.h>
+void t (void)
+{
+    pthread_atfork(0, 0, 0);
+}
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  lp_cv_has_pthread_atfork=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+( exit $ac_status )
+lp_cv_has_pthread_atfork=no
+
+fi
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+fi
+echo "$as_me:$LINENO: result: $lp_cv_has_pthread_atfork" >&5
+echo "${ECHO_T}$lp_cv_has_pthread_atfork" >&6
+    if test $lp_cv_has_pthread_atfork = yes; then
+        cat >>confdefs.h <<\_ACEOF
+#define HAS_PTHREAD_ATFORK 1
+_ACEOF
+
+    fi
+
     CFLAGS="$saveflags"
 else
     if test $enable_use_pthreads = yes; then
