Load 3.3.471 into branch/prcs-import-33.
git-svn-id: svn://svn.bearnip.com/ldmud/branch/prcs-import-33@1009 56160b6e-f8f8-0310-bd54-bccebfe6a2f2

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -3955,8 +3955,8 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 # configure at all, we fudge the CFLAGS a bit.
 
 save_cflags=$CFLAGS
-echo "For this test, I use '-g' instead of '$CFLAGS' as compiler flags."
 CFLAGS="-g"
+echo "For this test, '$CFLAGS' instead of '$save_cflags' is used as compiler flags."
 
 echo "$as_me:$LINENO: checking gcc/assembler float/branch incompatibility, e.g. on AIX" >&5
 echo $ECHO_N "checking gcc/assembler float/branch incompatibility, e.g. on AIX... $ECHO_C" >&6
@@ -9129,10 +9129,10 @@ echo $ECHO_N "checking for mySQL... $ECHO_C" >&6
 if test "${lp_cv_has_mysql+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  for TESTPATH in "" "$mysql_path" "$mysql_path/include" "/usr/local/mysql/include" "/usr/local/include" "/usr/include" "/usr/lib/mysql"; do
+  for TESTPATH in "" "${mysql_path}/include" "${mysql_path}" "/usr/local/mysql/include" "/usr/lib/mysql"; do
     saveflags="$CFLAGS"
     if test "x$TESTPATH" != "x"; then
-        CFLAGS="$CFLAGS -I$TESTPATH"
+        CFLAGS="-I$TESTPATH $CFLAGS"
     fi
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
@@ -9198,8 +9198,12 @@ _ACEOF
 
 
   if test $enable_use_mysql = yes; then
+    tmp=""
+
     if test "x$mysql_path" = "x"; then
-        echo "$as_me:$LINENO: checking for main in -lmysqlclient" >&5
+        if test -d "/usr/local/mysql/lib"; then
+            CFLAGS="$saveflags -L/usr/local/mysql/lib"
+            echo "$as_me:$LINENO: checking for main in -lmysqlclient" >&5
 echo $ECHO_N "checking for main in -lmysqlclient... $ECHO_C" >&6
 if test "${ac_cv_lib_mysqlclient_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -9243,12 +9247,108 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlclient_main" >&5
 echo "${ECHO_T}$ac_cv_lib_mysqlclient_main" >&6
 if test $ac_cv_lib_mysqlclient_main = yes; then
-  PKGLIBS="$PKGLIBS -lmysqlclient"
+  tmp="$PKGLIBS -L/usr/local/mysql/lib -lmysqlclient"
 fi
 
-    else
-        tmp=""
+        elif test -d "/usr/local/lib"; then
+            CFLAGS="$saveflags -L/usr/local/lib"
+            echo "$as_me:$LINENO: checking for main in -lmysqlclient" >&5
+echo $ECHO_N "checking for main in -lmysqlclient... $ECHO_C" >&6
+if test "${ac_cv_lib_mysqlclient_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmysqlclient  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
 
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_mysqlclient_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_mysqlclient_main=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlclient_main" >&5
+echo "${ECHO_T}$ac_cv_lib_mysqlclient_main" >&6
+if test $ac_cv_lib_mysqlclient_main = yes; then
+  tmp="$PKGLIBS -L/usr/local/mysql/lib -lmysqlclient"
+fi
+
+        else
+            echo "$as_me:$LINENO: checking for main in -lmysqlclient" >&5
+echo $ECHO_N "checking for main in -lmysqlclient... $ECHO_C" >&6
+if test "${ac_cv_lib_mysqlclient_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmysqlclient  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_mysqlclient_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_mysqlclient_main=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlclient_main" >&5
+echo "${ECHO_T}$ac_cv_lib_mysqlclient_main" >&6
+if test $ac_cv_lib_mysqlclient_main = yes; then
+  tmp="$PKGLIBS -lmysqlclient"
+fi
+
+        fi
+    else
         if test -d "${mysql_path}/lib/mysql"; then
             CFLAGS="$saveflags -L${mysql_path}/lib/mysql"
             echo "$as_me:$LINENO: checking for main in -lmysqlclient" >&5
@@ -9397,21 +9497,21 @@ if test $ac_cv_lib_mysqlclient_main = yes; then
 fi
 
         fi
+    fi
 
-        if test "x$tmp" = "x"; then
-            echo "mysqlclient library not found - disabling mySQL support"
-            if test "x$not_available" = "x"; then
+    if test "x$tmp" = "x"; then
+        echo "mysqlclient library not found - disabling mySQL support"
+        if test "x$not_available" = "x"; then
     not_available="use-mysql"
 else
     not_available="$not_available, use-mysql"
 fi
-            cdef_use_mysql="#undef"
-            enable_use_mysql="no"
-            mysql_path=
-            lp_cv_has_mysql="no"
-        else
-            PKGLIBS="$tmp"
-        fi
+        cdef_use_mysql="#undef"
+        enable_use_mysql="no"
+        mysql_path=
+        lp_cv_has_mysql="no"
+    else
+        PKGLIBS="$tmp"
     fi
   fi
 
